### PR TITLE
Add OTP 21.0 Support

### PR DESCRIPTION
**Pull request by walkr**
Update library to support Erlang OTP 21.0 version.

### CODE REVIEW

**Comment by walkr** [comment]
OTP 21.0 support added  in [this pull request](https://github.com/urbint/rox/pull/15)

**Comment by ayrat555** [comment]
Thanks! When will this PR be merged?

**Comment by glittershark** [comment]
Hey @walkr! Sorry it's taken us so long to get to this. Would you mind rewriting the commit history to follow the [semantic commit standards](https://seesparkbox.com/foundry/semantic_commit_messages) and making sure each of the commit messages have a body?

Meanwhile, I'll start working on a CONTRIBUTING.md so we don't have to keep asking people this :smile:

**Comment by glittershark** [comment]
Also, would you leave out the changelog changes for now? I'll just update that when I publish a new version.

**Comment by walkr** [comment]
Hey @glittershark! I'm a little busy at the moment, but I will try to get to it hopefully sometime next week.
Cheers!

**Comment by methyl** [comment]
Any chance to get this merged?

**Comment by l1x** [comment]
By the time this gets merged we can do it for v22. :)

**Comment by walkr** [comment]
@glittershark I've updated the commit messages as requested. Please push a new version as @l1x, @methyl and others are waiting for this repo to be updated. 😄

**Comment by glittershark** [comment]
hey - sorry for the delay in the response to this! We're working internally on policies, standards, and better documentation around open source, which'll definitely result in faster response times and a clearer contribution process for all of our repos, Rox included :smile:

**Comment by glittershark** [comment]
Published 2.3.0

**Pull request merged**
