### PR TITLE
List column families

### PR DESCRIPTION
**Pull request by octavonce**

### CODE REVIEW

**Comment by rschmukler** [comment]
Hey @octavonce thank you for the PR! Could you please recommit following our commit format for the repo:

```
feat: add list_cf/2

This commit introduces a function which will list column families inside an existing database.
```

It's helpful for autogenerating our changelog! Thanks again for the PR

**Comment by octavonce** [comment]
Ok, sure

**Comment by octavonce** [comment]
Done

**Comment by rschmukler** [comment]
Thanks @octavonce

**Pull request merged**
